name = "brendavegarealty"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "src/worker.ts"

[assets]
directory = "./out"
binding = "ASSETS"

[[kv_namespaces]]
binding = "STUDIO_KV"
id = "a5d099e3d9be4694859a6dbf009dd095"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "bvr-media"
